### ISSUE TITLE
Math rendering to html doesn't seem right

### ISSUE THREAD

**Issue by hanjoosten** [jgm/texmath#139]
I write a pandoc document programatically. In my Haskell application, I use texmath. I write a document, and somewhere it contains an Inlines section:

```.haskell
para (math "s= \\sqrt {foo}")
```

When I render this to .docx, there is no warning, and the rendering is as expected:

![image](https://user-images.githubusercontent.com/1159672/58035190-8b732c00-7b28-11e9-9d22-10ee8bcd14ce.png)

If I generate the same document, but now for html, I get a warning, saying:

```
[WARNING] Could not convert TeX math 's= \sqrt {foo}', rendering as TeX
```

This seems the case not only with `\sqrt{..}`, but also with `\overline{..}`, and possibly other tex functions that take parameters.

**Comment by hanjoosten** [comment]
In the [texmath demo site](https://johnmacfarlane.net/texmath.html), there is a proper rendering:

![image](https://user-images.githubusercontent.com/1159672/58035917-24ef0d80-7b2a-11e9-9efc-9d7e0029c589.png)

**Comment by jgm** [comment]
This is because, by default, pandoc tries to render
math in HTML using unicode characters.  That isn't
possible for things that require an overline, so
in such cases it just gives up and falls back to TeX.

Solution is to choose one of the many options
described for rendering math in HTML in the pandoc
manual.  Using pandoc as a library, see
writerHTMLMathMethod in WriterOptions.

**Comment by hanjoosten** [comment]
thanks!
