### ISSUE TITLE
Spacing with math operators in Pandoc output

### ISSUE THREAD

**Issue by cryptocraft** [jgm/texmath#143]
It would be helpful if spacing with \bmod could be improved in readTex / writePandoc.

readTeX, when processing `"a \bmod b"`, gives `[EIdentifier "a",EMathOperator "mod",EIdentifier "b"]`.  writePandoc renders this as `[Emph [Str "a"],Str "mod",Str "\8198",Emph [Str "b"]]`.  It would be better to have space before "mod" too.

**Comment by jgm** [comment]
Really this just concerns `writePandoc`, I guess.  And it's not specific to `mod`; it applies to any math operator coming after an identifier, I guess.

`addSpaces` there is based on Appendix G of the TeX Book.
We could change it to add a thinspace *before* a math operator (as well as after), but that might give bad results when the operator comes after, say, open parentheses.

We could add thin space after every EIdentifier.  That might actually give output more similar to TeX's -- if you write `$abc$`, the letters appear a bit spaced.

**Comment by cryptocraft** [comment]
When TeX handles `$a \bmod b$`, "a" and "b" are set in `Ord` atoms, and the "mod" produced by `\bmod` is set in a `Rel` atom.  TeX adds thick space before the `Rel` atom and before the "b" `Ord` atom, according to the table on page 170 of the TeXbook.

`addSpaces` in `writePandoc` implements something along the same lines as this table.

The particular problem with `\bmod` can be solved by interpreting it in `readTex` as `ESymbol Bin "mod"` rather than `EMathOperator "mod"` as at present - although how nicely that plays with other Writers I'll leave you to assess.

You're right though, that `addSpaces` could do more to mimic TeX.  It could treat `EIdentifier` and `ENumber` objects as `Ord` atoms in addition to the current treatment of `EOperator` objects as `Op` atoms and the various types of `ESymbol`.

I notice that the TeX definition of `\bmod` includes some hackery to ensure that the spaces are included even when it's used in e.g. sub- and superscripts: these spaces would otherwise disappear, according to the TeXbook table.  Perhaps therefore an improved `addSpaces` should ignore the parentheses in the table.

**Comment by jgm** [comment]
Tried it. Here are the differences:

- OMML/Word:  with the change, "mod" gets more spacing (definite improvement) and also appears in italics rather than roman face (maybe not good).

- MathML: identical output.

- TeX: with the change we get `a \mathrel{\text{mod}} c`; previously we got `a\operatorname{mod}c`.  Neither is ideal but this could be special-cased in the writer.

- Eqn:  previously we got `a "mod" c`, with the change, it's `a roman{" mod "} c`.  This is actually much better.

- Native: with the change we now get thin spaces around `mod`, as desired.

On the whole this is an improvement, and we can work around the rough edges.
