### ISSUE TITLE
docx to html conversion: inconsistent handling of subscripts

### ISSUE THREAD

**Issue by davidmckinnon** [jgm/texmath#151]
I am converting docx to html using pandoc (v2.9.1) with the '--mathjax' option called from conda Python (3.7.1). I am using Katex to render the equations. There are two issues that could arguably be viewed as inconsistent behavior. 

From the attached docx file you get the following output:

\[g_{\text{Na}}\]

\[g_{K}\]

\[g_{\text{Na}}\]

\[g_{K}\]
[test_1.docx](https://github.com/jgm/texmath/files/4022504/test_1.docx)

First, single character subscripts are not modified with \text, whereas two or more character subscripts are. This affects subsequent display in Katex. The unmodified single character is rendered as italic whereas the two character subscript is rendered as plain text. Since the default rendering in Word for subscripts is italics (as it is in Katex) it would seem that in both cases the pandoc output should be modified with \mathit not \text. 

Second, if you change the subscript to plain text in Word (as is done in the 3rd and 4th examples), this has no effect on the output, for both single and multiple character subscripts. Ideally both would be modified with '\mathrm'. It would seem that italic and non-italic subscripts should be distinguished by pandoc. Not sure if the OMML allows this.

**Comment by jgm** [comment]
Currently we parse an m:t element as an EIdentifier if it
contains a single letter, but an EText TextNormal
if it contains more than one. This may not be the right behavior,
but it's a bit hard to know because omml doesn't make the
same kind of distinction between identifiers and text as
MathML or TeX.

To see the difference:
```
% texmath -t tex -f native
[ESub (EIdentifier "A") (EText TextNormal "Na")]
^D
A_{\text{Na}}
% texmath -t tex -f native
[ESub (EIdentifier "A") (EIdentifier "Na")]
^D
A_{Na}
```

**Comment by BBreiden** [comment]
We are currently trying to convert a large Word document (~900 pages) containing many formulas to tex. Pandoc does a great job! Thank you very much for your work. 🙂 

However, we have run into the same problem with some of the formulas. I inspected the OMML for these cases and I think it would be safe to split all m:t elements _without any additional properties_ into one EIdentifier for each letter (or one multi-letter EIdentifier). In all cases where we have more than one letter in an m:t element and don't want it to be treated as separate identifiers (e.g.  plain text in a formula), the m:t has been marked as "normal" by the m:nor property in OMML.

What do you think?

**Comment by jgm** [comment]
In test_1.docx above, the difference is that in the 3rd and 4th cases we have the property
```xml
                <m:rPr>
                  <m:sty m:val="p" />
                </m:rPr>
```
Everything else is the same.
"p" means "plain"

**Comment by BBreiden** [comment]
Wouldn't it be possible, to use the absence of any additional stylings in the first two examples to parse them as EIdentifiers and to parse the third and forth example both as EText, because they have additional stylings? So instead of using the length of the m:t element to decide, if it is an identifier or plain text, use the properties attached to the m:t element. (Of course, one would base the decision on the presence of specific stylings like m:nor or m:sty)

I suppose that the LaTex or HTML result would then look like to the input in word, or am I wrong?

**Comment by jgm** [comment]
Yes, I am exploring this approach.
