### ISSUE TITLE
binary distribution

### ISSUE THREAD

**Issue by lastdates** [jgm/texmath#75]
hey, can you post binary distribution as installing all the dependencies is too much

**Comment by jgm** [comment]
+++ Lastdates [May 06 15 12:33 ]:
>   hey, can you post binary distribution as installing all the
>   dependencies is too much

Sorry, it's a fair amount of work to generate binary
packages for the various platforms.  I do it for pandoc,
but I don't have time to do it for texmath.

**Comment by r-gaia-cs** [comment]
@lastdates can you let me know why you want the binary of texmath?

I think that if you install Pandoc you will get what you want.

**Comment by lastdates** [comment]
@r-gaia-cs I need to convert OMML to Tex, but I don't have experience with Haskell, does Pandoc support conversion of OMML to Tex?

**Comment by r-gaia-cs** [comment]
>  I need to convert OMML to Tex

OK.

> does Pandoc support conversion of OMML to Tex?

**I don't have Microsoft Office installed in my machine.** Pandoc doesn't convert equations created using LibreOffice and stored as `*.docx`. I got

~~~
$ pandoc -f docx -t latex test.docx   
Inline equation:
~~~

instead of

~~~

~~~
$ pandoc -f docx -t latex test.docx   
Inline equation: $\sqrt{2}$
~~~

I believe that LibreOffice is saving the OMML correct:

~~~
$ unzip -c test.docx word/document.xml
Archive:  test.docx
  inflating: word/document.xml       
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" mc:Ignorable="w14 wp14"><w:body><w:p><w:pPr><w:pStyle w:val="Normal"/><w:rPr></w:rPr></w:pPr><w:r><w:rPr></w:rPr><w:t>Inline equation:</w:t></w:r><w:r><w:rPr></w:rPr></w:r><m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e><m:r><w:rPr><w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/></w:rPr><m:t xml:space="preserve">2</m:t></m:r></m:e></m:rad></m:oMath></w:p><w:sectPr><w:type w:val="nextPage"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:left="1134" w:right="1134" w:header="0" w:top="1134" w:footer="0" w:bottom="1134" w:gutter="0"/><w:pgNumType w:fmt="decimal"/><w:formProt w:val="false"/><w:textDirection w:val="lrTb"/></w:sectPr></w:body></w:document>
~~~

but I have no experience with OMML.

@lastdates maybe you want to open a bug in Pandoc?

**Comment by jgm** [comment]
+++ Lastdates [May 07 15 01:04 ]:
>   [1]@r-gaia-cs I need to convert OMML to Tex, but I don't have
>   experience with Haskell, does Pandoc support conversion of OMML to Tex?

Pandoc will convert OMML inside docx files, yes.
If you want to convert OMML directly, you should

    cabal install texmath -fexecutable

**Comment by jgm** [comment]
Note:  it should be easier now to install from source, using the stack tool.
Install stack: https://github.com/commercialhaskell/stack
Then in the texmath repository,

    stack setup
    stack install --flag texmath:executable
